Feature/simonova kafka 1
ValentinaSimonova20/JavaSchool pull request #1
Opened 2024-12-22 15:35 UTC by ValentinaSimonova20

2024-12-23 17:19 UTC, Liman26 requested changes

2024-12-23 17:19 UTC, Liman26 commented on pom.xml
> +            <version>1.8</version>
Все версии выносите в properties

2024-12-23 17:19 UTC, Liman26 commented on src/main/java/sbp/school/kafka/Main.java
> +        producerService.send();
Выносим в тесты, в исходниках только реализация сервиса

2024-12-23 17:19 UTC, Liman26 commented on src/main/java/sbp/school/kafka/ProducerService.java
> +                                System.out.println("ExecutionException " + exception.getMessage());
Давай логгер подключим

2024-12-23 17:19 UTC, Liman26 commented on src/main/java/sbp/school/kafka/ProducerService.java
> +                                new Transaction(transactionType, 100L, "счет", LocalDateTime.now())
Тестовые данные тоже в тесты

2024-12-23 17:19 UTC, Liman26 commented on src/main/java/sbp/school/kafka/serializer/JsonTransactionSerializer.java
> +        return null;
Потенциальный NPE. Лучше возвращать пустой массив или подбрасывать исключение

2024-12-23 17:19 UTC, Liman26 commented on src/main/java/sbp/school/kafka/ProducerService.java
> +                                "quickstart-events-partitions",
Почему топик хардкодом?

2024-12-23 21:05 UTC, ValentinaSimonova20 commented on src/main/java/sbp/school/kafka/serializer/JsonTransactionSerializer.java
> +        return null;
поправила

2024-12-23 21:07 UTC, ValentinaSimonova20 commented on src/main/java/sbp/school/kafka/ProducerService.java
> +                                new Transaction(transactionType, 100L, "счет", LocalDateTime.now())
> Тестовые данные тоже в тесты

убрала отсюда, добавила в тест

2024-12-23 21:07 UTC, ValentinaSimonova20 commented on src/main/java/sbp/school/kafka/ProducerService.java
> +                                "quickstart-events-partitions",
@Liman26 убрала в  application.properties

2024-12-23 21:08 UTC, ValentinaSimonova20 commented on src/main/java/sbp/school/kafka/ProducerService.java
> +                                System.out.println("ExecutionException " + exception.getMessage());
@Liman26 добавила

2024-12-23 21:08 UTC, ValentinaSimonova20 commented on src/main/java/sbp/school/kafka/Main.java
> +        producerService.send();
@Liman26 добавила тест

2024-12-23 21:08 UTC, ValentinaSimonova20 commented on pom.xml
> +            <version>1.8</version>
@Liman26 Поправила

2024-12-27 20:36 UTC, Liman26 approved these changes

2024-12-30 14:12 UTC, merged