вторая дз
ValentinaSimonova20/JavaSchool pull request #2
Opened 2024-12-24 21:16 UTC by ValentinaSimonova20

2024-12-27 20:43 UTC, Liman26 requested changes

2024-12-27 20:43 UTC, Liman26 commented on src/main/java/sbp/school/kafka/consumer/ConsumerService.java
> +                kafkaConsumer.commitSync();
Если при обработке пачки сообщений упадёт ошибка не на первой, то все остальные тоже не будут закомичены. Этот вариант событий подходит нам?

2024-12-27 20:43 UTC, Liman26 commented on src/main/java/sbp/school/kafka/deserializer/JsonTransactionDeserializer.java
> +        throw new RuntimeException("Получили null в значении");
Здесь лучше подбрасывать ошибку десериализации, посмотрите как это делается в готовых десериализаторах

2024-12-30 14:54 UTC, ValentinaSimonova20 commented on src/main/java/sbp/school/kafka/consumer/ConsumerService.java
> +                kafkaConsumer.commitSync();
@Liman26 не подходит
переделала на комит по определенным партициям

2024-12-30 14:55 UTC, ValentinaSimonova20 commented on src/main/java/sbp/school/kafka/deserializer/JsonTransactionDeserializer.java
> +        throw new RuntimeException("Получили null в значении");
@Liman26 исправила

2025-01-03 06:03 UTC, Liman26 approved these changes

2025-01-05 11:57 UTC, merged